import localFont from "next/font/local";
import "./globals.css";
import { Bebas_Neue } from 'next/font/google';
import Header from "./components/Header";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const bebasNeue = Bebas_Neue({
  subsets: ['latin'],
  display: 'swap',
  weight: "400"
})

export const metadata = {
  title: "Auriane Le Perdriel | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
